export type FullFinancialDataRow = {
  id: string;
  fiscal_year: number;
  fiscal_quarter: string;
  consolidation_type: string;
  revenue: number;
  operating_income: number;
  net_income: number;
  total_assets: number;
  equity: number;
  interest_bearing_debt: number | null;
  operating_cf: number | null;
  investing_cf: number | null;
  shares_outstanding: number | null;
  interest_expense: number | null;
  current_stock_price: number | null;
  cash_and_equivalents: number | null;
  current_assets: number | null;
  investments_and_other_assets: number | null;
  current_liabilities: number | null;
  non_current_liabilities: number | null;
  shareholders_equity: number | null;
  beta: number | null;
  input_unit: string;
};
